### ISSUE TITLE
request hatası 

### ISSUE THREAD

**Issue by sumeyyecelikkk** [malibayram91/temel_tensoflow2_egitimi#1]
Merhabalar öncelikle emeginize sağlık güzelbir paylaşım olmuş,  ben sizin gösterdiğiniz şekilde hepsi buradadan yrum çekmeye çalışştım ama daha ilk aşamada istek yapınca hata aldım acaba neyden kaynaklanıyor olabilirim, ekran görüntüsü ektedir. 
şimdiden teşekkürler
![request](https://user-images.githubusercontent.com/77808832/105411588-a161ba00-5c44-11eb-8f64-c0be9db632cd.jpg)

**Comment by malibayram** [comment]
hepsiburada.com bu şekilde erişimi engellemiş `headers` ekleyerek sorunu çözebilirsiniz. Ben örnek bir `headers` ekliyorum.
`headers = {
    'authority': 'www.hepsiburada.com',
    'cache-control': 'max-age=0',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'service-worker-navigation-preload': 'true',
    'sec-fetch-site': 'none',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-user': '?1',
    'sec-fetch-dest': 'document',
    'accept-language': 'tr,ar;q=0.9,tr-TR;q=0.8,en-US;q=0.7,en;q=0.6',
    'cookie': 'isGlobalIp=0; __gads=ID=66a49919da5a9403:T=1608011532:S=ALNI_MbFTYoEWsoO2UgwbwY73AmbXpHlzg; _abck=78DA792923314A777ED53B5024489870~0~YAAQrIYUAi3D7kd2AQAAPcj0ZAUbKJeLBe5XCb9hljKKGY6LDnbne8J3uhRh2AI2L+2qfCo9/oSO2xYr2yU09ynioWGhBVXgCKnmcR+I2Pg9JQ9H6SbIJkiAmEa0CCsPYBeMswJKW+2xagQw0kPU/XJtpVdSkrhDJoGhj7on6i0SBW3/kSIPY8O8jSPNLVum1XR5T1JcwuZXCeKgQ/9bTa6afHcn/TnbGeze6GCmIcjHYTkaBegvxRGTB7f66jHc0TAhGgqGfUivEGD9vRa5DwNBPfNURFtRM8klb+pFSvoUt3RFSgXERRlMoUON54Fr3SHUJEOvqStmUfnz7oHTyj69UZcFUfpWeCI0~-1~||-1||~-1; hbus_anonymousId=ba2c10e2-bdc0-4aee-ba25-283b68770ad3; _fbp=fb.1.1608011532506.712838097; SFSESSIONID=af5ba624-61aa-4e62-ad47-fe011ec772ef; _hjid=adf9f742-d5e6-49c5-aa49-8166dcc67a9c; ab.storage.deviceId.a19ee87d-6625-49ed-ad8c-f427b0067dec=%7B%22g%22%3A%22b5ec5071-6961-9dc4-9918-e88b562b4d4c%22%2C%22c%22%3A1608011538269%2C%22l%22%3A1608011538269%7D; cookieconsentanon=false%7C12%2F19%2F2020%2C%2011%3A07%3A04%20PM; anon=1889C45AE7FE8DEBD701B589EFEB437A1B49886E92D3766EE30D0EB6F61FACCF6C2C0719A8761736B04B250520B5D4453DE589BCEEE99E7635536A39B95A88E7B223031995C1FFD0E7B280890F4C7E01D60EF8583C94538739A6E4FD3648C0614A0C2228DE480467AA529A1DCE638730EAD86B3306D7761F7DCDAD72FBC47279668F1328D2AA40DB3EB723FF255C6D3178908C8034D8D49A28C829412C2ABAFD43217C4BDB61C7BC34C2ACE2E804E57DB25B5D2BCC6DB2B9BD1E7CE73CF0DA620FE194FA000D16B0F6AADC060A477EB221CD3A5E5F2C13C5BF674BED2D3CCB4170232B291AF684D6E7CF8A93B2891A3F6134B6AA1835361F5C674CFAA880DE1A01611265C80F3FFC66909689674882C62CB20B8D3F0DA9CB1E4C0D025D39F1420BEC258EFB1366CA1F80A37EEAA3A187B3917CA8F97E5F4294F9DE161B7332026029F958DC1219B273792DB6; newhbv1=1889C45AE7FE8DEBD701B589EFEB437A1B49886E92D3766EE30D0EB6F61FACCF6C2C0719A8761736B04B250520B5D4453DE589BCEEE99E7635536A39B95A88E7B223031995C1FFD0E7B280890F4C7E01D60EF8583C94538739A6E4FD3648C0614A0C2228DE480467AA529A1DCE638730EAD86B3306D7761F7DCDAD72FBC47279668F1328D2AA40DB3EB723FF255C6D3178908C8034D8D49A28C829412C2ABAFD43217C4BDB61C7BC34C2ACE2E804E57DB25B5D2BCC6DB2B9BD1E7CE73CF0DA620FE194FA000D16B0F6AADC060A477EB221CD3A5E5F2C13C5BF674BED2D3CCB4170232B291AF684D6E7CF8A93B2891A3F6134B6AA1835361F5C674CFAA880DE1A01611265C80F3FFC66909689674882C62CB20B8D3F0DA9CB1E4C0D025D39F1420BEC258EFB1366CA1F80A37EEAA3A187B3917CA8F97E5F4294F9DE161B7332026029F958DC1219B273792DB6; jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MDg1ODI0ODQsImV4cCI6MTYwODU4OTY4NCwiaWF0IjoxNjA4NTgyNDg0LCJVc2VySWQiOiI4NjY0YTUyZi1lNDdjLTQ2NDUtYWM2NC0zYzdiZDQ0MmM4MzQiLCJUaXRsZSI6Ik1laG1ldCBBbGkgQmF5cmFtIiwiRmlyc3ROYW1lIjoiTWVobWV0IEFsaSIsIkxhc3ROYW1lIjoiQmF5cmFtIiwiRW1haWwiOiJtYWxpYmF5cmFtOTFAZ21haWwuY29tIiwiSXNBdXRoZW50aWNhdGVkIjoiVHJ1ZSIsIkFwcEtleSI6IkFGN0YyQTM3LUNDNEItNEYxQy04N0ZELUZGMzY0MkY2N0VDQiIsIlByb3ZpZGVyIjoiSGVwc2lidXJhZGEiLCJwIjp7InQiOltdfX0.frimPdYy1oyyRugPrvUHMxd26Y1UUvQUOgwfW7W9d1c; eJwt=ttT1DojhgOUTOBUmIS%2BAJrQegpHCWh25Zea3HeCiHlY4v5POtvZIJo2VHixqnc1r7Gvlw9LRr4enBQjwnwDCJzPnSoXSN3zhTnjLYQ593RwnnESZGo2XXF2LpofR4Of3cEWELJwE5d%2Ff8tC8PbEm%2B3sMlg6%2B7RB87FEI8OplAVBEaWiTtjJNsFKCDknPGrn9ER0Bq7oZf70Pb%2Bqk76vPnMHbkca11zHih5da2nrmTDUIR4UPt%2FW%2BhLN1KHiHTjEbjf70%2BdFyMAhi3iEKeJybeYVsPp1vHpCwmNteMUJJWIqd0q9L0H1ib28Q8H2vJsWTwvHy8HBwie6bcXjvK3s6CQP6Wxn%2FPeIxB92I1e90XpbrEcvpIJIM%2FJN8ZmHqJZcyXp7CH33uTt8q39pN7N7%2BdZY5uP0PvPm9iCBIz6QM8Lk5007Y%2FYVz3Hwrpzlmch2wO%2BSJ8yfXPUFRzj9OearIhc5nL4PaoZcT7fnB2nfAyDY2gryOA2aOOtNUUun9hngrMkiOzUT6izluBVaqMsnAe4uDRD8hgOTUAOgZ3B7jrq0Tz3VT3OjyadrfhR7osU%2BVlZEVy5sx2JXJy4LuDuTXQ1jjl0f%2FOYcCL5diNgk5Aa2Lp9hdmkkq%2FCpNFUHpn2%2Fu8NOXu2ExnXx3Cq0spisYyGV3WFQOKkY%2Fyly2Dbl7yyo%3D; cookieconsentauth=true; ab.storage.userId.a19ee87d-6625-49ed-ad8c-f427b0067dec=%7B%22g%22%3A%228664a52f-e47c-4645-ac64-3c7bd442c834%22%2C%22c%22%3A1608582487055%2C%22l%22%3A1608582487055%7D; _fbc=fb.1.1608583131898.IwAR1bxm64qFn-owmhLlkcgrpZi7kLbTlHatC_q1f197eZvoZvD7sQzC7c86s; wt_fa=lv~1608583160565|1639687160565#cv~1|1639687160565#fv~2020-12|1639687160566#; _gaexp=GAX1.2.RC-UiEzYTJ2hdOPP9007ag.18711.0; _gcl_aw=GCL.1610396480.CjwKCAiAi_D_BRApEiwASslbJ--vyGZ6x61tonrNmGgDSZcdIKFA1KczR_jjj0vQkPQCDjFoOHnJHRoCAJoQAvD_BwE; _gac_UA-834379-1=1.1610396481.CjwKCAiAi_D_BRApEiwASslbJ--vyGZ6x61tonrNmGgDSZcdIKFA1KczR_jjj0vQkPQCDjFoOHnJHRoCAJoQAvD_BwE; __zlcmid=126jjBz6EMcVoLi; RT="z=1&dm=hepsiburada.com&si=38sejd5x07u&ss=kjt0hfpv&sl=0&tt=0"; wt3_eid=%3B289941511384204%7C2160801153100016214%232161097753400216567; _ga=GA1.1.778580476.1608011532; ab.storage.sessionId.a19ee87d-6625-49ed-ad8c-f427b0067dec=%7B%22g%22%3A%228a3d923a-204d-242b-36d9-f339b0fdfd4c%22%2C%22e%22%3A1610979335336%2C%22c%22%3A1610977535337%2C%22l%22%3A1610977535337%7D; hbus_sessionId=507172e3-06be-443b-b5c0-e2035df02a45%7C1610979350091; _ga_44CSPTX731=GS1.1.1610977535.12.1.1610977559.0; HB_S_MR=1; AKA_A2=A; ak_bmsc=A9907E7718AFA2D7D9FA3300E243A3DD02160AECED35000049ED0960B78C256A~plefYwR6/IuelzAVyWIFlAmegsJ6RQWPDoZkEred9NAK/9mVSLez/AoiInBYvdmAYECeYAjzxSVukkTlDr5MUgN0q8PLhxsiVm0bJwHuuJUTEMvRru9C/itsZmh5JFcoUMPoWXNh7/l8HCr/CsFalM77pjnqUFjWPo1dYbIFSkKtzI1xQUt7xOpZe2bNhI6s2rFTYFE313CmNcYjE13kcr0Ubr3Yhw9ovlJdOSx0Bw150=; bm_sz=981D1966DCEA8EBE340366FE5EAF66C1~YAAQ7AoWAuHWRB13AQAAD+nGJgqI8wXDwWo7rE4TIAT8fEXsYy+pxnUkmyQj8yJDkD/UavMCHZZ6b+XOKolHnQqqhIXpTyyY1MUKK0oGWET6VBE8EAGTuEjKxoSnkzdR2I0FSYDPkonXo/NlH/AYfRreEw0dHg/lkF0utZTA3CYOE7JzhBY+YnvKvrMkVM6x3420v5k=; bm_sv=FBDF3CB7B55A4610EB9CBC1075E22BEA~Eiq9jeF9j3tGXgRQ0B2iDaK1Pgzl1VJLa0TMKFvVaGhdgEW6mmQ+q/hbUxm2pbiNBiLJ9dy1cEKjoqJm/4q5Dt2tTqGDrdpPFuYJZC01R5yEGA1UY4iQaY2DXx6PUfKN7VLm93nrCyyhqJjMd666P15LSKkwKtXMIvyw+bLQLaE=',
}`

istek şekli de şu şekilde olacak: `istek = urllib.request.Request(url, headers=headers)`
diğer kısımlar aynı kalacak.

**Comment by malibayram** [comment]
headers almak için: 
![image](https://user-images.githubusercontent.com/18294669/105413449-2a79f080-5c47-11eb-8eac-f541c559ff30.png)
sonradan kopyaladığınız şeyi [https://curl.trillworks.com/](https://curl.trillworks.com/) buradan python koduna çevirebilirsiniz. `headers`ı her seferinde oluşturmak zorunda kalınabilir.

**Comment by sumeyyecelikkk** [comment]
Teşekkürler emeginize sağlık
